// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIx3nhB12AzS7NQA38CIMAi59n7got_n0',
    appId: '1:1015286724095:web:b9bb562459610e86f9a3ca',
    messagingSenderId: '1015286724095',
    projectId: 'product-db-3e6ef',
    authDomain: 'product-db-3e6ef.firebaseapp.com',
    databaseURL: 'https://product-db-3e6ef-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-3e6ef.appspot.com',
    measurementId: 'G-3RK0SPHVVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_DJm37X06Bi9-G2ct3Yvn81z0JsMR3E',
    appId: '1:1015286724095:android:795493be2837356ef9a3ca',
    messagingSenderId: '1015286724095',
    projectId: 'product-db-3e6ef',
    databaseURL: 'https://product-db-3e6ef-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-3e6ef.appspot.com',
  );

}